from enum import Enum


class MessageType(bytes, Enum):
    MSG_TYPE_INIT = b'\x00'
    MSG_TYPE_CONTROL = b'\x01'
    MSG_TYPE_DATA = b'\x02'
    MSG_TYPE_END = b'\x03'


class SensingTypeEnumType(str, Enum):
    switch = 'switch'
    button = 'button'
    level = 'level'
    levelSwitch = 'levelSwitch'
    windowHandle = 'windowHandle'
    contactSensor = 'contactSensor'
    occupancySensor = 'occupancySensor'
    motionDetector = 'motionDetector'
    fireDetector = 'fireDetector'
    smokeDetector = 'smokeDetector'
    heatDetector = 'heatDetector'
    waterDetector = 'waterDetector'
    gasDetector = 'gasDetector'
    alarmSensor = 'alarmSensor'
    powerAlarmSensor = 'powerAlarmSensor'
    dayNightIndicator = 'dayNightIndicator'


class SensingStateEnumType(str, Enum):
    on = 'on'
    off = 'off'
    toggle = 'toggle'
    level = 'level'
    levelUp = 'levelUp'
    levelDown = 'levelDown'
    levelStart = 'levelStart'
    levelStop = 'levelStop'
    levelAbsolute = 'levelAbsolute'
    levelRelative = 'levelRelative'
    levelPercentageAbsolute = 'levelPercentageAbsolute'
    levelPercentageRelative = 'levelPercentageRelative'
    pressed = 'pressed'
    longPressed = 'longPressed'
    released = 'released'
    changed = 'changed'
    started = 'started'
    stopped = 'stopped'
    paused = 'paused'
    middle = 'middle'
    up = 'up'
    down = 'down'
    forward = 'forward'
    backwards = 'backwards'
    open = 'open'
    closed = 'closed'
    opening = 'opening'
    closing = 'closing'
    high = 'high'
    low = 'low'
    day = 'day'
    night = 'night'
    detected = 'detected'
    notDetected = 'notDetected'
    alarmed = 'alarmed'
    notAlarmed = 'notAlarmed'

